# Offline patch build - see director/Dockerfile.patch for the full explanation.
#
#   $env:DOCKER_BUILDKIT = "0"
#   docker build -f authentication/Dockerfile.patch -t iep/authentication:latest authentication
FROM iep/authentication:latest

COPY . /service/
